
# apt mirror
apt_repo_path: ""

mirror_apt_url: "http://mirrors.ustc.edu.cn/{{ apt_repo_path }}/" 
mirror_apt_distro: "{{ ansible_distribution_release }}" # 或 bionic, focal, etc.


# apt packages
apt_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - vim
  - git
  - net-tools
  - iproute2
  - python3-pip

# custom yum repo 配置
roller_repo_url: ""
roller_repo_name: "RollerRepo"

# custom hosts
custom_hosts: []
  # - ip: "192.168.1.100"
  #   hostname: "example.com"