
# apt mirror
mirror_apt_url: "http://mirrors.ustc.edu.cn/{{ ansible_distribution | lower }}" # 或 debian/
mirror_apt_security_url: "http://mirrors.ustc.edu.cn/{{ ansible_distribution | lower }}" # 或 debian/updates/
mirror_apt_distro: "{{ ansible_distribution_release }}" # 或 bionic, focal, etc.


# apt packages
apt_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - vim
  - git
  - tmux
  - net-tools
  - iputils-ping
  - iproute2
  - iftop
  - htop
  - python3-pip

# For CentOS
mirror_dnf_yum_url: "http://mirrors.ustc.edu.cn/almalinux/" # 或 centos/
mirror_dnf_yum_baseos: "BaseOS"
mirror_dnf_yum_appstream: "AppStream"
mirror_dnf_yum_extras: "extras"

# Roller repo 配置
roller_repo_url: ""
roller_repo_name: "RollerRepo"

custom_hosts:
  # - ip: "192.168.1.100"
  #   hostname: "example.com"