- name: Set APT repository variables based on distribution and architecture
  set_fact:
    apt_repo_path: ""
    apt_repo_pool: ""

- name: Set variables for Ubuntu distribution
  set_fact: 
    apt_repo_path: "{{ 'ubuntu-ports' if ansible_architecture == 'aarch64' else 'ubuntu' }}"
    apt_repo_pool: "main restricted universe multiverse"
  when: ansible_distribution == 'Ubuntu'

- name: Set variables for Debian distribution
  set_fact:
    apt_repo_path: "debian"
    apt_repo_pool: "main contrib non-free non-free-firmware"
  when: ansible_distribution == 'Debian'

- name: debian | 配置 repo mirror 
  template:
    src: apt_sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  when: apt_repo_path is defined and apt_repo_path != ""

- name: debian | 更新 repo 缓存
  apt:
    update_cache: yes

- name: debian | 安装基础软件包
  apt:
    name: "{{ apt_base_packages }}"
    state: present
    update_cache: yes

- name: 临时关闭 AppArmor 服务
  service:
    name: apparmor
    state: stopped     
  when:
    - "'apparmor.service' in ansible_facts.services"
    - ansible_facts.services['apparmor.service'].state == 'running' 
  tags: [apparmor]

- name: 永久关闭 AppArmor
  service:
    name: apparmor
    enabled: no
  when:
    - "'apparmor.service' in ansible_facts.services" 
  tags: [apparmor]