- name: 更新 /etc/hosts 条目 (删除旧行并添加新行)
  import_tasks: update_hosts.yml

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: redhat.yml
  when: 
  - ansible_os_family == 'RedHat' 

- name: Configure SSH client settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    regexp: "^{{ item.regexp }}" 
    line: "{{ item.line }}"     
    state: present
    create: true             
    mode: '0644'    
  loop:
    - { regexp: 'UserKnownHostsFile', line: 'UserKnownHostsFile /dev/null' }
    - { regexp: 'StrictHostKeyChecking', line: 'StrictHostKeyChecking no' }
    - { regexp: 'HashKnownHosts', line: 'HashKnownHosts no' }
